version: "0.0.1"

networks:
  kafka-net:
services:

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_HEAP_OPTS: -Xmx512m -Xms512m
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server kafka:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 3

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    depends_on:
      kafka:
        condition: service_started
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: "true"
    networks:
      - kafka-net


  server:  # Add your server as a service
    build: .  # Use the Dockerfile in the current directory
    depends_on:
      - kafka
    networks:
      - kafka-net
    environment:
      BOOTSTRAP_SERVERS: kafka:9092 # Pass Kafka address as env variable


  # Run 3 client instances for federated learning
  client1:  # Client 1
    build: ../Client
    depends_on:
      - kafka
      - server
    networks:
      - kafka-net
    environment:
      BOOTSTRAP_SERVERS: kafka:9092 # Pass Kafka address as env variable
      CLIENT_ID: "1"

  client2:  # Client 2
    build: ../Client
    depends_on:
      - kafka
      - server
    networks:
      - kafka-net
    environment:
      BOOTSTRAP_SERVERS: kafka:9092 # Pass Kafka address as env variable
      CLIENT_ID: "2"

  client3:  # Client 3
    build: ../Client
    depends_on:
      - kafka
      - server
    networks:
      - kafka-net
    environment:
      BOOTSTRAP_SERVERS: kafka:9092 # Pass Kafka address as env variable
      CLIENT_ID: "3"